[USER]
;User Details
USERNAME="";Username (The name you want to use on the remote pData site)
[LAP_DISPLAY]
;Lap Status Display
SHOW_HISTORY=True;Show Lap History (If you want to show the Invalid/Pit/OK status of the last 5 laps of the session)